### PR TITLE
Fix markdown (and a few bug fixes)

### LINKED ISSUE #423: Comments tab: sometimes you end up writing too many words for something so simple it could be described in ten words or less, cf this title
http://i.imgur.com/KbaB346.png

Suggestion:

***

**Leave a comment below**

Leave feedback on this user by typing your comment below. reddit markdown is supported.

***

### LINKED ISSUE #424: Inconsistent capitalization
http://i.imgur.com/jrXxqKu.png

The second button is not capitalized correctly.

### PR DESCRIPTION
**Pull request by YaManicKill**
Fixes #424 and fixes #423

### CODE REVIEW

File: assets/markdown/remapURLs.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+module.exports = function (value) {
+  var userRegex = /(<a href=")(\/[u]\/[a-zA-Z_\/-]+)(">)(.*)(<\/a>)/g;
+  var usersReplaced = value.replace(userRegex, "$1https://www.reddit.com$2$3$4$5 ($1$2$3FlairHQ$5)");
+  var subRegex = /(<a href=")(\/[r]\/[a-zA-Z_\/-]+)(">)(.*)(<\/a>)/g;
```
Comment (not-an-aardvark) [inline assets/markdown/remapURLs.js]: We should change the `.*` here to `.*?`, otherwise it'll do a greedy search and might map more than we want it to.

Also, note that it won't correctly link `u/username` or `r/subreddit` like reddit does.

**Comment by not-an-aardvark** [comment]
Do we want to link to the FlairHQ profile in [this case](https://i.gyazo.com/b3be7752767510eee8b9305305cce428.png)?

File: assets/markdown/remapURLs.js (hunk 1 above)
Comment (YaManicKill) [inline assets/markdown/remapURLs.js]: I should probably just change it to essentially be a username again, so it doesn't allow spaces etc. That will solve the other issue as well. Will look later.

**Comment by YaManicKill** [comment]
No, we don't. Good call, I'll look at that.

**Comment by not-an-aardvark** [comment]
var userRegex = /(<a href=")(\/[u]\/[a-zA-Z_\/-]+)(">)(.*)(<\/a>)\/?\2/g;
    var subRegex = /(<a href=")(\/[r]\/[a-zA-Z_\/-]+)(">)(.*)(<\/a>)\/?\2/g;

**Comment by YaManicKill** [comment]
Wait, what does this do?

**Comment by not-an-aardvark** [comment]
It should match `<a href='/u/username'>/u/username` and `<a href='/u/username'>u/username` but not `<a href='/u/username'>somethingelse`. Haven't had time to test it fully though, so it might not work yet.

File: assets/markdown/remapURLs.js [hunk 2]
```diff
@@ -0,0 +1,6 @@
+module.exports = function (value) {
+  var userRegex = /(<a href=")(\/[u]\/[a-zA-Z_\/-]+)(">)\/?\2(.*?)(<\/a>)/g;
+  var userReplaced = value.replace(userRegex, "$1https://www.reddit.com$2$3$2$5 ($1$2$3FlairHQ$5)");
+  var subRegex = /(<a href=")(\/[r]\/[a-zA-Z_\/-]+)(">)\/?\2(.*?)(<\/a>)/g;
+  return userReplaced.replace(subRegex, "$1https://www.reddit.com$2$3$2$5");
+};
```
Comment (not-an-aardvark) [inline assets/markdown/remapURLs.js]: Figured out the regex. Use this instead:

```javascript
module.exports = function (value) {
  var userRegex = /(<a href=")\/(u\/[a-zA-Z0-9_\/-]+)(">)\/?\2(.*?)(<\/a>)/g;
  var userReplaced = value.replace(userRegex, "$1https://www.reddit.com/$2$3$2$5 ($1$2$3FlairHQ$5)");
  var subRegex = /(<a href=")\/(r\/[a-zA-Z0-9_\/-]+)(">)\/?\2(.*?)(<\/a>)/g;
  return userReplaced.replace(subRegex, "$1https://www.reddit.com/$2$3$2$5");
};
```

**Comment by YaManicKill** [comment]
Any existing issues you have with this, @not-an-aardvark, or are we cool to merge? Would be good to get this out the way.
