### PR TITLE
Fix Reddit.js error

### LINKED ISSUE #370: Reddit.js error
fhq-0 TypeError: Cannot read property 'headers' of undefined
    at updateRateLimits (/var/www/flairhq/api/services/Reddit.js:148:10)
    at Request.parseResponse [as _callback] (/var/www/flairhq/api/services/Reddit.js:36:7)
    at self.callback (/var/www/flairhq/node_modules/request/request.js:198:22)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/var/www/flairhq/node_modules/request/request.js:867:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at connectErrorNT (net.js:993:8)
    at doNTCallback2 (node.js:430:9)
    at process._tickDomainCallback (node.js:385:17)

### PR DESCRIPTION
**Pull request by not-an-aardvark**
Resolves #370

### CODE REVIEW

File: api/services/Reddit.js [hunk 1]
```diff
@@ -145,7 +145,7 @@ exports.checkModeratorStatus = function (refreshToken, username, subreddit, call
 };
 
 var updateRateLimits = function (res) {
-  if (res.headers['x-ratelimit-remaining'] && res.headers['x-ratelimit-reset']) {
+  if (res.headers && res.headers['x-ratelimit-remaining'] && res.headers['x-ratelimit-reset']) {
```
Comment (YaManicKill) [inline api/services/Reddit.js]: res && res.headers && 

The issue was res was undefined, not the headers.
