### PR TITLE
Fix #441

### LINKED ISSUE #441: When adding a trade, client incorrectly handles usernames that start with /u/
...leading to stuff like [this](https://i.gyazo.com/5979350686205185421380585ee2e7c6.png).

### PR DESCRIPTION
**Pull request by not-an-aardvark**
To fix the database entries that have been affected by this:

```javascript
db.reference.find({user2: /\/u\/.*/}).forEach(function(ref) {
   db.reference.update({_id: ref._id }, {$set: {user2: ref.user2.slice(3)}});
})
```
(I would recommend making a backup first, though I'm fairly confident that the command won't cause any issues.)

### CODE REVIEW

File: assets/js/indexCtrl.js [hunk 1]
```diff
@@ -47,8 +47,7 @@ module.exports = function ($scope) {
     $scope.addRefError = "";
     $scope.indexOk.addRef = false;
     $scope.indexSpin.addRef = true;
-    var url = "/reference/add",
-      user2 = $scope.addInfo.user2;
+    var url = "/reference/add";
     $scope.addRefError = $scope.validateRef($scope.addInfo);
```
Comment (not-an-aardvark) [inline assets/js/indexCtrl.js]: tl;dr: `$scope.addInfo.user2` gets modified by `validateRef()`, but we were still sending the old value to the server for whatever reason.

**Comment by YaManicKill** [comment]
Ran the script against the production database. Worked fine. However, we do seem to have a bunch of ones from way back that have user2 as "http://www.reddit.com/u/user" so we'll need to fix them sometime.
